name: Deploy to Azure

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: myapp-api-7vhw6fhdrelcs
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Build with dotnet
      run: dotnet build OneTime.API/OneTime.API.csproj --configuration Release
    
    - name: Publish with dotnet
      run: dotnet publish OneTime.API/OneTime.API.csproj -c Release -o ./publish
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'